# Generated by Django 6.0.6 on 2026-06-24 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilcliente',
            name='direccion_secundaria',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='perfilcliente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/'),
        ),
    ]
