# Generated by Django 6.0.6 on 2026-07-02 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_mensajecontacto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensajecontacto',
            options={'ordering': ['-fecha'], 'verbose_name': 'Mensaje de contacto', 'verbose_name_plural': 'Mensajes de contacto'},
        ),
    ]
