# Generated by Django 6.0.6 on 2026-07-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_alter_mensajecontacto_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='direccion',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='pedido',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nombre_completo',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='pedido',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
